service: wedding-gift-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: post

custom:
  esbuild:
    bundle: true
    minify: false

    packager: 'yarn'
plugins:
  - serverless-esbuild
  - serverless-offline
