service: wedding-gift-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: post
 
plugins:
  - serverless-plugin-typescript
  - serverless-offline
