//ESSE MANO VAI SER CHAMADO PELO ADAPTER PRIMARY FAZER O BERIMBOLO DE CRIAR O USUARIO
//ABSTRACAO PARA CRIAR UM USUARIO INDIFERENTE DE ONDE FOR EXECUTADO
//IMPORTANTE----- ELE NAO DEVE SABER NADA DO CARA QUE TA CHAMANDO ELE

